build_task:
  name: android kernel build
  timeout_in: 120m
  # trigger_type: manual  # 如果需要手动触发构建，请取消注释此行
  # only_if: $CIRRUS_BRANCH == "main"
  container:
    image: ubuntu:20.04
    kvm: true
    cpu: 8
    memory: 24G
  env:
    GITHUB_TOKEN: ENCRYPTED[!c9b9a362a2217549ddfce5fed43f26082d948062290d4d77b3f20c268110aaf59af017dc4f71660256d4a4b8b607a234!]
  prepare_script:
    - git clone https://github.com/wym1987/test.git test
    - mv ebpf-ci-test/*.sh .
    - bash ./prebuild.sh